// import { useI18n } from 'vue-i18n';
// const { t } = useI18n();

//  t('save')
//  {{ t('reset') }}

import { apiSetup, apiCall } from '../apiCall';

import { createI18n } from 'vue-i18n';

const i18n = createI18n({
  legacy: false,
  locale: 'ru',
  fallbackLocale: 'en',
  messages: {
    en: {
      add: 'Add',
      add_route_params: 'Add parameter',
      autocomplete_controller: 'Autocomplete',
      autocomplete_liveWare_controller: 'LiveWire controller',
      autocomplete_simple_controller: 'Controller',
      available_all_params: 'Any parameters allowed',
      available_selected_params: 'Only selected allowed',
      bind_params: 'Bind parameters',
      blade_comment: 'Blade comments',
      blade_snippet: 'Blade snippets',
      cache_created: 'Cache created',
      cache_published: 'Cache published',
      cancel: 'Cancel',
      choose_files: 'Choose files',
      copy_as_imgcode: 'Copy Img',
      copy_path: 'Copy path',
      copy: 'Copy',
      cut: 'Cut',
      crawler: 'Crawler',
      create: 'Create',
      create_file: 'Create file',
      create_folder: 'Create folder',
      delete: 'Delete',
      delete_published_cache: 'Delete published cache',
      delete_storage: 'Delete storage',
      duplicate_overwrite: 'Duplicate — will be overwritten',
      edit: 'Edit',
      enter_number: 'Enter number',
      error: 'Error',
      errors: 'Errors',
      file_name: 'File name',
      file_saved: 'File saved',
      file_was_loaded: 'Loaded',
      formatted: 'Formatted',
      go_selected: 'Go to article by selected word',
      goto_article: 'Go to article',
      is_route: 'Route enabled',
      insert: 'Insert',
      login_as_user: 'Log in as this user',
      logged_in_as: 'Logged in as',
      menu_on: 'Visible in menu',
      name_file: 'File name',
      name_folder: 'Folder name',
      new_name: 'New name',
      new_tab: 'New tab',
      no: 'No',
      now_reading: 'Checking now',
      ok: 'Ok',
      only_admin: 'Admin only',
      publish_storage: 'Publish storage',
      public_deleted: 'Public deleted',
      ready: 'Ready',
      ready_url_rout: 'Ready URL',
      rename: 'Rename',
      reset: 'Reset',
      route_params: 'Route parameters',
      route_post: 'Post reguest',
      save: 'Save',
      saved: 'Saved',
      search: 'Search',
      setup_reset: 'Settings reset',
      setup_saved: 'Settings saved',
      start: 'Start',
      stop: 'Stop',
      storage_deleted: 'Storage deleted',
      submit: 'Done',
      total: 'Total',
      upload: 'Upload',
      upload_files: 'File upload',
      url_saved: 'URL saved',
      use_controller: 'Use controller',
      use_getpatams: 'Use GET parameters',
      utm_enable: 'Enable UTM ?=utm...',
      user_list_loaded: 'List loaded',
      was_deleted: 'Deleted ',
      mail: 'Mail',
      feed_code: 'Code',
      feed_code_locked_help: 'The feed already holds records, so a field keeps its code. The code is how the application reads the value: renaming it turns every blade and controller that used the old name into an error, while the values stay where they were.',
      feed_group_string: 'String fields',
      feed_no_free_slot: 'No free slots of this type left',
      feed_save_schema: 'Save schema',
      feed_string_help: 'Code — the name the application uses. Label — the caption in the admin panel. default — the value a new record starts with. Unic — the value has to be unique inside the feed. validation — Laravel rules as one string, for example: required|string|min:3|max:255',
      feed_cut_done: 'Cut:',
      feed_group_delete_ask: 'Delete the group?',
      feed_paste_done: 'Moved',
      feed_feeds_count: 'Feeds',
      feed_group: 'Group',
      feed_items_count: 'Records',
      feed_name: 'Feed',
      feed_no_feeds: 'No feeds in this group',
      feed_no_groups: 'No groups yet',
      feed_title: 'Feeds',
      mail_tab_messages: 'Messages',
      mail_tab_addresses: 'Emails',
      mail_address_email: 'Email',
      mail_address_blocked: 'Blocked',
      mail_sent: 'Sent',
      mail_queue: 'Queue',
      mail_from: 'From',
      mail_to: 'To',
      mail_subject: 'Subject',
      mail_sent_at: 'Sent at',
      mail_scheduled_at: 'Scheduled at',
      mail_attempts: 'Attempts',
      mail_status: 'Status',
      mail_errors_title: 'Delivery errors',
      mail_no_errors: 'No errors',
      mail_delete_confirm: 'Delete this message?',
      mail_deleted: 'Message deleted',
      mail_empty: 'No messages',
      mail_load_more: 'Load more',
      mail_status_queued: 'Queued',
      mail_status_sent: 'Sent',
      mail_status_delivered: 'Delivered',
      mail_status_open: 'Opened',
      mail_status_retrying: 'Delivery error',
      mail_status_failed: 'Failed',
      mail_status_emailblocked: 'Blocked',
      mail_details_title: 'Message',
      mail_details_button: 'Details',
      mail_reply_to: 'Reply-To',
      mail_close: 'Close',
      mail_raw_title: 'Raw message',
      yes: 'Yes',
    },

    ru: {
      add: 'Добавить',
      add_route_params: 'Добавить параметр',
      autocomplete_controller: 'Автозаполнение',
      autocomplete_liveWare_controller: 'LiveWare контроллер',
      autocomplete_simple_controller: 'Контроллер',
      available_all_params: 'Доступны любые параметры',
      available_selected_params: 'Доступны только',
      bind_params: 'Привязывать параметры',
      blade_comment: 'комментарии блейда',
      blade_snippet: 'снипеты блейда',
      cache_created: 'Кеш создан',
      cache_published: 'Кеш опубликован',
      cancel: 'Отмена',
      choose_files: 'Выбрать файлы',
      copy_as_imgcode: 'Копировать Img',
      copy_path: 'Копировать путь',
      copy: 'Копировать',
      cut: 'Вырезать',
      crawler: 'Краулер',
      create: 'Создать',
      create_file: 'Создать файл',
      create_folder: 'Создать папку',
      delete: 'Удалить',
      delete_published_cache: 'Удалить опубликованный кеш',
      delete_storage: 'Удалить storage',
      duplicate_overwrite: 'копия, будет переписан',
      edit: 'Редактировать',
      enter_number: 'Введите число',
      error: 'Ошибка',
      errors: 'Ошибки',
      insert: 'Вставить',
      file_name: 'Имя файла',
      file_saved: 'Файл сохнанен',
      file_was_loaded: 'Загружен',
      formatted: 'Отформатировано',
      go_selected: 'перейти в статье по выбранному слову',
      goto_article: 'перейти на статью',
      is_route: 'Раут включен',
      login_as_user: 'Войти под этим пользователем',
      logged_in_as: 'Выполнен вход как',
      menu_on: 'Видно в меню',
      name_file: 'Имя файла',
      name_folder: 'Имя папки',
      new_name: 'Новое имя',
      new_tab: 'Новой вкладке',

      no: 'Нет',
      now_reading: 'Сейчас проверяется',
      ok: 'Ок',
      only_admin: 'Только Админ',
      publish_storage: 'Опубликовать storage',
      public_deleted: 'Public удален',
      ready: 'Готово',
      ready_url_rout: 'Готовый url',
      rename: 'Переименовать',
      reset: 'Сбросить',
      route_params: 'Параметры маршрута',
      route_post: 'Post запрос',
      save: 'Сохранить',
      saved: 'Сохранено',
      search: 'Поиск',
      setup_reset: 'Параметры сброшены',
      setup_saved: 'Параметры сохранены',
      start: 'Старт',
      stop: 'Стоп',
      storage_deleted: 'Storage удален',
      submit: 'Готово',
      total: 'Всего',
      upload: 'Загрузить',
      upload_files: 'Загрузка файлов',
      url_saved: 'url_сохранен',
      use_controller: 'Испольовать контроллер',
      use_getpatams: 'Использовать GET параметры',
      utm_enable: 'Разрешить Utm ?=utm...',
      user_list_loaded: 'Список считан',
      was_deleted: 'Удален ',
      mail: 'Почта',
      feed_code: 'Код',
      feed_code_locked_help: 'В ленте уже есть записи, поэтому поле сохраняет свой code. Code — это то, как приложение читает значение: переименование превращает в ошибку каждый блейд и контроллер со старым именем, а сами значения остаются на месте.',
      feed_group_string: 'Строковые поля',
      feed_no_free_slot: 'Свободных слотов этого типа не осталось',
      feed_save_schema: 'Сохранить схему',
      feed_string_help: 'Code — имя, которым пользуется приложение. Label — подпись в админке. default — значение новой записи. Unic — значение должно быть уникальным внутри ленты. validation — правила Laravel одной строкой, например: required|string|min:3|max:255',
      feed_cut_done: 'Вырезано:',
      feed_group_delete_ask: 'Удалить группу?',
      feed_paste_done: 'Перенесено',
      feed_feeds_count: 'Лент',
      feed_group: 'Группа',
      feed_items_count: 'Записей',
      feed_name: 'Лента',
      feed_no_feeds: 'В группе нет лент',
      feed_no_groups: 'Групп пока нет',
      feed_title: 'Ленты',
      mail_tab_messages: 'Сообщения',
      mail_tab_addresses: 'Емайлы',
      mail_address_email: 'Емайл',
      mail_address_blocked: 'Блокировка',
      mail_sent: 'Отправленные',
      mail_queue: 'В очереди',
      mail_from: 'Отправитель',
      mail_to: 'Получатель',
      mail_subject: 'Тема',
      mail_sent_at: 'Отправлено',
      mail_scheduled_at: 'Запланировано',
      mail_attempts: 'Попытки',
      mail_status: 'Статус',
      mail_errors_title: 'Ошибки доставки',
      mail_no_errors: 'Ошибок нет',
      mail_delete_confirm: 'Удалить это письмо?',
      mail_deleted: 'Письмо удалено',
      mail_empty: 'Писем нет',
      mail_load_more: 'Показать ещё',
      mail_status_queued: 'В очереди',
      mail_status_sent: 'Отправлено',
      mail_status_delivered: 'Доставлено',
      mail_status_open: 'Открыто',
      mail_status_retrying: 'Ошибка доставки',
      mail_status_failed: 'Сбой',
      mail_status_emailblocked: 'Заблокировано',
      mail_details_title: 'Письмо',
      mail_details_button: 'Подробнее',
      mail_reply_to: 'Reply-To',
      mail_close: 'Закрыть',
      mail_raw_title: 'Raw письмо',
      yes: 'Да',
    },
  },
});

export const i18nReady = new Promise((resolve) => {
  (async () => {
    const result = await apiSetup({
      command: 'getIniParams',
    });
    const loc = result?.LANGUAGE || 'en'; //
    console.log(loc);
    i18n.global.locale.value = loc;
    resolve(loc);
  })();
});

export default i18n;
