// import { useI18n } from 'vue-i18n';
// const { t } = useI18n();

//  t('save')
//  {{ t('reset') }}

import { apiSetup, apiCall } from '../apiCall';

import { createI18n } from 'vue-i18n';

const i18n = createI18n({
  legacy: false,
  locale: 'ru',
  fallbackLocale: 'en',
  messages: {
    en: {
      add: 'Add',
      add_route_params: 'Add parameter',
      autocomplete_controller: 'Autocomplete',
      autocomplete_liveWare_controller: 'LiveWire controller',
      autocomplete_simple_controller: 'Controller',
      available_all_params: 'Any parameters allowed',
      available_selected_params: 'Only selected allowed',
      bind_params: 'Bind parameters',
      blade_comment: 'Blade comments',
      blade_snippet: 'Blade snippets',
      cache_created: 'Cache created',
      cache_published: 'Cache published',
      cancel: 'Cancel',
      choose_files: 'Choose files',
      copy_as_imgcode: 'Copy Img',
      copy_path: 'Copy path',
      copy: 'Copy',
      cut: 'Cut',
      crawler: 'Crawler',
      cron_add: 'Add task',
      cron_broken: 'The task will not run',
      cron_controller: 'Controller (article|method)',
      cron_controller_hint: 'Article and a public method of its controller, separated by |, for example dataCache|task',
      cron_delete_confirm: 'Delete the task?',
      cron_deleted: 'Task deleted',
      cron_done: 'Done',
      cron_empty: 'No tasks',
      cron_enabled: 'Active',
      cron_expression: 'Schedule',
      cron_expression_hint: 'Five fields, server time: minute hour day month weekday',
      cron_form_edit: 'Task',
      cron_form_new: 'New task',
      cron_last_run: 'Last run',
      cron_name: 'Name',
      cron_params: 'Parameters',
      cron_params_hint: 'json object, goes to the method as one array. Empty is fine',
      cron_run_now: 'Run now',
      cron_saved: 'Task saved',
      create: 'Create',
      create_file: 'Create file',
      create_folder: 'Create folder',
      delete: 'Delete',
      delete_published_cache: 'Delete published cache',
      delete_storage: 'Delete storage',
      duplicate_overwrite: 'Duplicate — will be overwritten',
      edit: 'Edit',
      enter_number: 'Enter number',
      error: 'Error',
      errors: 'Errors',
      file_name: 'File name',
      file_saved: 'File saved',
      file_was_loaded: 'Loaded',
      formatted: 'Formatted',
      go_selected: 'Go to article by selected word',
      goto_article: 'Go to article',
      image_cache: 'Image cache',
      image_cache_clear: 'Clear the image cache completely',
      image_cache_clear_btn: 'Clear',
      image_cache_cleanup: 'Delete the unused files from the cache',
      image_cache_cleanup_btn: 'Delete',
      image_cache_cleared: 'Files deleted',
      is_route: 'Route enabled',
      insert: 'Insert',
      login_as_user: 'Log in as this user',
      logged_in_as: 'Logged in as',
      menu_on: 'Visible in menu',
      name_file: 'File name',
      name_folder: 'Folder name',
      new_name: 'New name',
      new_tab: 'New tab',
      no: 'No',
      now_reading: 'Checking now',
      ok: 'Ok',
      only_admin: 'Admin only',
      publish_storage: 'Publish storage',
      public_deleted: 'Public deleted',
      ready: 'Ready',
      ready_url_rout: 'Ready URL',
      rename: 'Rename',
      reset: 'Reset',
      route_params: 'Route parameters',
      route_post: 'Post reguest',
      save: 'Save',
      saved: 'Saved',
      search: 'Search',
      setup_reset: 'Settings reset',
      setup_saved: 'Settings saved',
      start: 'Start',
      stop: 'Stop',
      storage_deleted: 'Storage deleted',
      submit: 'Done',
      total: 'Total',
      upload: 'Upload',
      upload_files: 'File upload',
      url_saved: 'URL saved',
      use_controller: 'Use controller',
      use_getpatams: 'Use GET parameters',
      utm_enable: 'Enable UTM ?=utm...',
      user_list_loaded: 'List loaded',
      was_deleted: 'Deleted ',
      mail: 'Mail',
      feed_code: 'Code',
      feed_code_locked_help: 'The feed already holds records, so a field keeps its code. The code is how the application reads the value: renaming it turns every blade and controller that used the old name into an error, while the values stay where they were.',
      feed_field_delete_ask: 'Remove the field from the schema?',
      feed_json_bad: 'JSON is not valid.',
      feed_group_bigint: 'bigInt',
      feed_item_delete_ask: 'Delete the record?',
      feed_item_held: 'The record is still linked from:',
      feed_group_ops: 'Group operations',
      feed_items_delete_ask: 'Delete the marked records?',
      feed_items_deleted: 'Deleted:',
      feed_mark_all: 'select all',
      feed_order_own: 'Own order of the feed',
      feed_no_items: 'No records yet',
      feed_text_result: 'result',
      format_code: 'Format the markup',
      feed_text_preview: 'preview',
      feed_text_heading: 'Heading',
      feed_text_subheading: 'Subheading',
      feed_text_normal: 'Normal',
      feed_text_link: 'Link',
      feed_text_link_href: 'Address, empty removes the link',
      feed_text_clear: 'Clear formatting',
      feed_string_over: 'the tail will be cut off when saved',
      feed_image_none: 'no image',
      feed_image_choose: 'choose file',
      feed_image_not_chosen: 'no file chosen',
      feed_image_upload: 'upload',
      feed_image_crop: 'crop',
      feed_image_back: 'back to image',
      feed_image_name_from: 'take the file name from',
      feed_image_alt_from: 'take the alt from',
      feed_image_name_bad: 'the file name takes latin letters, digits and a dash only',
      feed_image_name_long: 'the file name is longer than allowed:',
      feed_image_min: 'minimum',
      feed_image_current: 'current',
      feed_image_paste: 'or paste with Ctrl+V',
      feed_image_delete_ask: 'Delete the image?',
      feed_position: 'Position',
      feed_show_on_list: 'List',
      feed_list_format: 'Format',
      feed_list_format_help: 'Date mask for the list, PHP letters: d m y Y H i s. Empty — as stored',
      feed_visible: 'Visible',
      feed_visible_any: 'show all records',
      feed_visible_only: 'show visible records only',
      feed_hidden_only: 'show hidden records only',
      feed_slug: 'Slug',
      feed_slug_from: 'Slug',
      feed_slug_from_help: 'Make the slug of a record out of this field. One source per feed, click again to clear it',
      feed_group_link: 'Links',
      feed_link_choose: 'choose',
      feed_link_feed: 'Feed',
      feed_link_field: 'Field shown to the operator',
      feed_link_same_group: 'Only feeds of this group can be linked',
      feed_group_bool: 'Boolean',
      feed_group_date: 'Date',
      feed_group_string: 'Strings',
      feed_no_free_slot: 'No free slots of this type left',
      feed_save_schema: 'Save schema',
      feed_list_order: 'Order of the records',
      feed_list_order_help: 'The list opens in this order. Only a string field or a date: the ordering is done by the database, and a field of the json container has no column of its own',
      feed_list_order_own: 'own order of the feed',
      feed_list_order_asc: 'ascending',
      feed_list_order_desc: 'descending',
      feed_view_article: 'Article that shows a record',
      feed_view_article_help: 'Name of the article the site shows records with. The address of a record is /<article>/<slug>, and the link to it appears in the record form. Empty — no link',
      feed_view_item: 'View',
      feed_form_order: 'Order in the record form',
      feed_form_order_help: 'Order of the fields on the record page. All fields are here: a field hidden from the form could not be filled in',
      api_error: 'Error',
      api_bad_request: 'Bad request',
      api_network: 'Network error',
      api_bad_answer: 'Invalid answer',
      api_unknown: 'Unknown error',
      api_link_copied: 'Link copied',
      api_link_copy_error: 'The link is not copied',
      art_cut: 'Cut:',
      art_pasted: 'Pasted',
      art_created: 'Created',
      art_root_keep: 'The root is better left alone',
      art_delete_ask: 'Delete?',
      art_delete_no_parent: 'Delete failed: the parent is not found',
      art_delete_failed: 'Delete failed, reload the page',
      art_deleted: 'Deleted',
      art_copied: 'Copied',
      art_export: 'Export',
      check_articles: 'Article check',
      check_hint: 'Finds and repairs at once; what was repaired is in the report',
      check_done: 'Repaired',
      check_clean: 'There was nothing to repair',
      check_reports: 'Reports',
      check_reports_empty: 'none yet',
      imp_file: 'File',
      imp_date: 'Date',
      imp_size: 'Size',
      imp_mode: 'Mode',
      imp_partial: 'Partial',
      imp_full: 'Full',
      imp_mode_hint: 'Partial hangs the tree of the file onto the site. Full wipes the site and raises the file in its place.',
      imp_check: 'Check',
      imp_check_first: 'The import is opened by a clean check',
      imp_run: 'Import',
      imp_run_ask: 'Import? The site is about to change.',
      imp_no_file: 'No file chosen',
      imp_report_ok: 'The file is fine, the import is open',
      imp_report_bad: 'The file will not do',
      imp_done: 'done',
      imp_done_all: 'Done',
      imp_file_failed: 'Files of the article {name} were not written: {error}. The tree is imported, fix this article and save it — the import does not need repeating.',
      imp_attach_root: 'The file hangs {name} onto {parent}, and there is no such article on the site: {name} goes to the root as the last leaf',
      imp_clean: 'No errors, nothing of the site is lost',
      imp_trees_hint: 'The birch is the tree of the file, the oak is the tree of the site. Only errors and collisions are reported: where a name meets a name, the article of the oak goes with everything under it.',
      imp_replace: 'The article {name} is in the birch and in the oak — the one of the oak will be deleted',
      imp_drop: 'Parent {parent}: the birch has no article {name}, the oak has, it will be deleted',
      imp_e_json: 'The file does not read as json',
      imp_e_not_list: 'The file is not a list of articles',
      imp_e_empty: 'There are no articles in the file',
      imp_e_row: 'Row {line}: this is not an article',
      imp_e_name: 'Row {line}: no name',
      imp_e_name_bad: 'Row {line}: the name {name} — latin letters, digits, dash and underscore only',
      imp_e_dup: 'The name {name} is in the file twice',
      imp_e_root_partial: 'The file carries root: such a file is raised by a full import only',
      imp_e_ring: 'A ring in the file: the articles point at each other in a circle',
      art_drag_error: 'Drag and drop failed',
      art_not_selected: 'No article selected',
      art_help: 'Help',
      art_find: 'find',
      feed_conditions: 'Conditions',
      feed_sort_asc: 'ascending',
      feed_sort_desc: 'descending',
      feed_per_page_after: 'records per page',
      feed_field_visible: 'visibility',
      feed_field_created: 'created at',
      feed_field_updated: 'updated at',
      feed_sorting: 'Sorting',
      feed_pagination: 'Pagination',
      feed_size_mb: 'MB',
      feed_size_kb: 'KB',
      feed_recipe_by_id: 'Record by id',
      feed_recipe_create: 'Create a record',
      feed_recipe_change: 'Change a record by id',
      feed_recipe_remove: 'Delete a record by id',
      feed_recipe_list: 'List builder',
      feed_tab_data: 'Data',
      feed_tab_structure: 'Structure',
      feed_string_help: 'Code — the name the application uses. Label — the caption in the admin panel. default — the value a new record starts with. Unic — the value has to be unique inside the feed. validation — Laravel rules as one string, for example: required|string|min:3|max:255',
      feed_cut_done: 'Cut:',
      feed_group_delete_ask: 'Delete the group?',
      feed_feed_delete_ask: 'Delete the feed?',
      feed_feed_not_empty: 'The feed has records, it is not deleted',
      feed_paste_done: 'Moved',
      feed_feeds_count: 'Feeds',
      feed_group: 'Group',
      feed_items_count: 'Records',
      feed_name: 'Feed',
      feed_no_feeds: 'No feeds in this group',
      feed_no_groups: 'No groups yet',
      feed_title: 'Feeds',
      mail_tab_messages: 'Messages',
      mail_tab_addresses: 'Emails',
      mail_address_email: 'Email',
      mail_address_blocked: 'Blocked',
      mail_sent: 'Sent',
      mail_queue: 'Queue',
      mail_from: 'From',
      mail_to: 'To',
      mail_subject: 'Subject',
      mail_sent_at: 'Sent at',
      mail_scheduled_at: 'Scheduled at',
      mail_attempts: 'Attempts',
      mail_status: 'Status',
      mail_errors_title: 'Delivery errors',
      mail_no_errors: 'No errors',
      mail_delete_confirm: 'Delete this message?',
      mail_deleted: 'Message deleted',
      mail_empty: 'No messages',
      mail_load_more: 'Load more',
      mail_status_queued: 'Queued',
      admin_new_password: 'Password of the new admin',
      admin_new_password_once: 'Copy it now: it is shown once. A forgotten one is replaced by editing.',
      admin_password_keep: 'new password, empty — keep the current one',
      mail_status_sending: 'Sending',
      mail_status_sent: 'Sent',
      mail_status_delivered: 'Delivered',
      mail_status_open: 'Opened',
      mail_status_retrying: 'Delivery error',
      mail_status_failed: 'Failed',
      mail_status_emailblocked: 'Blocked',
      mail_details_title: 'Message',
      mail_details_button: 'Details',
      mail_reply_to: 'Reply-To',
      mail_close: 'Close',
      mail_raw_title: 'Raw message',
      mcp_agent: 'Agent',
      mcp_command: 'Start command',
      mcp_start: 'start',
      mcp_password: 'Password',
      mcp_password_title: 'Additional password',
      mcp_no_config: 'No configAI.php, the section does not work. The file is expected at',
      mcp_no_password: 'The password is empty, the section is off. Set a password in',
      mcp_no_rules: 'The agent has no rules and will not be started. Expected file:',
      mcp_no_agents: 'configAI.php has no agents',
      mcp_session: 'Session',
      mcp_started: 'The session is started',
      mcp_reread: 'Reread',
      mcp_reread_help: 'Show everything that scrolled above the screen',
      mcp_send: 'Send',
      mcp_send_hint: 'Ctrl+Enter sends, Enter breaks the line',
      mcp_finish: 'Finish',
      mcp_finish_title: 'How to finish',
      mcp_closing: 'The exit command is sent',
      mcp_stopped: 'The session is over',
      mcp_leave: 'The agent is still running. Leave the page?',
      mcp_prompts: 'Prompts',
      mcp_prompt_add: 'Add prompt',
      mcp_prompt_name: 'Name',
      mcp_prompt_text: 'Text of the prompt',
      mcp_prompts_empty: 'Nothing saved yet',
      mcp_prompts_saved: 'Prompts saved',
      mcp_close: 'Close',
      mcp_kill_all: 'Kill my sessions',
      mcp_kill_help: 'Kills every agent started by you, on this page or another',
      mcp_kill_confirm: 'Kill all your agent sessions?',
      mcp_killed: 'Sessions killed',

      archive: 'Archive',
      archive_empty: 'No versions yet: the archive starts with the first save',
      archive_when: 'When',
      archive_who: 'Who',
      archive_body: 'Blade of the article',
      archive_controller: 'Controller',
      archive_copy_hint: 'The text is read only: take a piece of it and close, or restore the whole version.',
      archive_back: 'To the list',
      archive_restore: 'Restore',
      archive_restore_confirm: 'Restore this version? The article as it is now goes into the archive.',
      archive_restored: 'The version is restored',
      archive_exit: 'Exit',
      archive_days_now: 'The archive of article versions keeps {days} days',
      archive_days_forever: 'The archive of article versions is kept forever',
      archive_purge: 'Delete versions of deleted articles',
      archive_purge_confirm: 'Delete the versions of articles that no longer exist? There is no way back from this.',
      archive_purged: 'Versions deleted',
      archive_no_deleted: 'nothing from deleted articles',

      mcp_title: 'Token for МСП over https',
      mcp_intro: 'With this token an agent on your own machine works with the site through МСП tools and nothing else.',
      mcp_no_token: 'No token. The address answers 401 to everybody.',
      mcp_issued: 'Issued',
      mcp_last_used: 'Last call',
      mcp_ip: 'Address',
      mcp_state: 'State',
      mcp_alive: 'Alive: {idle} min without calls left, {life} min of life left',
      mcp_dead: 'Expired, take a new one',
      mcp_get: 'Get a token',
      mcp_get_again: 'Get a new one',
      mcp_reissue_confirm: 'A new token kills the old one, an agent running with it will stop. Continue?',
      mcp_revoke: 'Revoke',
      mcp_revoke_confirm: 'Revoke the token? The agent will stop right away.',
      mcp_revoked: 'The token is revoked',
      mcp_once: 'The token is shown once. Copy it now: the site keeps only a hash.',
      mcp_copy: 'Copy',
      mcp_copied: 'Copied',
      mcp_url: 'Address of МСП',
      mcp_export_hint: 'Before letting an agent work, export the root: right click on root in the tree → Export. To roll back, import that file in the full mode.',
      yes: 'Yes',
    },

    ru: {
      add: 'Добавить',
      add_route_params: 'Добавить параметр',
      autocomplete_controller: 'Автозаполнение',
      autocomplete_liveWare_controller: 'LiveWare контроллер',
      autocomplete_simple_controller: 'Контроллер',
      available_all_params: 'Доступны любые параметры',
      available_selected_params: 'Доступны только',
      bind_params: 'Привязывать параметры',
      blade_comment: 'комментарии блейда',
      blade_snippet: 'снипеты блейда',
      cache_created: 'Кеш создан',
      cache_published: 'Кеш опубликован',
      cancel: 'Отмена',
      choose_files: 'Выбрать файлы',
      copy_as_imgcode: 'Копировать Img',
      copy_path: 'Копировать путь',
      copy: 'Копировать',
      cut: 'Вырезать',
      crawler: 'Краулер',
      cron_add: 'Добавить задачу',
      cron_broken: 'Задача не отработает',
      cron_controller: 'Контроллер (статья|метод)',
      cron_controller_hint: 'Статья и публичный метод её контроллера через |, например dataCache|task',
      cron_delete_confirm: 'Удалить задачу?',
      cron_deleted: 'Задача удалена',
      cron_done: 'Выполнено',
      cron_empty: 'Задач нет',
      cron_enabled: 'Активна',
      cron_expression: 'Расписание',
      cron_expression_hint: 'Пять полей, время сервера: минута час день месяц день недели',
      cron_form_edit: 'Задача',
      cron_form_new: 'Новая задача',
      cron_last_run: 'Последний запуск',
      cron_name: 'Название',
      cron_params: 'Параметры',
      cron_params_hint: 'json-объект, уезжает в метод одним массивом. Можно пусто',
      cron_run_now: 'Выполнить сейчас',
      cron_saved: 'Задача сохранена',
      create: 'Создать',
      create_file: 'Создать файл',
      create_folder: 'Создать папку',
      delete: 'Удалить',
      delete_published_cache: 'Удалить опубликованный кеш',
      delete_storage: 'Удалить storage',
      duplicate_overwrite: 'копия, будет переписан',
      edit: 'Редактировать',
      enter_number: 'Введите число',
      error: 'Ошибка',
      errors: 'Ошибки',
      insert: 'Вставить',
      file_name: 'Имя файла',
      file_saved: 'Файл сохнанен',
      file_was_loaded: 'Загружен',
      formatted: 'Отформатировано',
      go_selected: 'перейти в статье по выбранному слову',
      goto_article: 'перейти на статью',
      image_cache: 'Кеш картинок',
      image_cache_clear: 'Полностью очистить кеш картинок',
      image_cache_clear_btn: 'Очистить',
      image_cache_cleanup: 'Удалить из кеша неиспользованные файлы',
      image_cache_cleanup_btn: 'Удалить',
      image_cache_cleared: 'Удалено файлов',
      is_route: 'Раут включен',
      login_as_user: 'Войти под этим пользователем',
      logged_in_as: 'Выполнен вход как',
      menu_on: 'Видно в меню',
      name_file: 'Имя файла',
      name_folder: 'Имя папки',
      new_name: 'Новое имя',
      new_tab: 'Новой вкладке',

      no: 'Нет',
      now_reading: 'Сейчас проверяется',
      ok: 'Ок',
      only_admin: 'Только Админ',
      publish_storage: 'Опубликовать storage',
      public_deleted: 'Public удален',
      ready: 'Готово',
      ready_url_rout: 'Готовый url',
      rename: 'Переименовать',
      reset: 'Сбросить',
      route_params: 'Параметры маршрута',
      route_post: 'Post запрос',
      save: 'Сохранить',
      saved: 'Сохранено',
      search: 'Поиск',
      setup_reset: 'Параметры сброшены',
      setup_saved: 'Параметры сохранены',
      start: 'Старт',
      stop: 'Стоп',
      storage_deleted: 'Storage удален',
      submit: 'Готово',
      total: 'Всего',
      upload: 'Загрузить',
      upload_files: 'Загрузка файлов',
      url_saved: 'url_сохранен',
      use_controller: 'Испольовать контроллер',
      use_getpatams: 'Использовать GET параметры',
      utm_enable: 'Разрешить Utm ?=utm...',
      user_list_loaded: 'Список считан',
      was_deleted: 'Удален ',
      mail: 'Почта',
      feed_code: 'Код',
      feed_code_locked_help: 'В ленте уже есть записи, поэтому поле сохраняет свой code. Code — это то, как приложение читает значение: переименование превращает в ошибку каждый блейд и контроллер со старым именем, а сами значения остаются на месте.',
      feed_field_delete_ask: 'Убрать поле из схемы?',
      feed_json_bad: 'JSON не валиден.',
      feed_group_bigint: 'bigInt',
      feed_item_delete_ask: 'Удалить запись?',
      feed_item_held: 'На запись ссылаются:',
      feed_group_ops: 'Групповые операции',
      feed_items_delete_ask: 'Удалить отмеченные записи?',
      feed_items_deleted: 'Удалено:',
      feed_mark_all: 'выделить все',
      feed_order_own: 'Свой порядок ленты',
      feed_no_items: 'Записей пока нет',
      feed_text_result: 'результат',
      format_code: 'Причесать разметку',
      feed_text_preview: 'предпросмотр',
      feed_text_heading: 'Заголовок',
      feed_text_subheading: 'Подзаголовок',
      feed_text_normal: 'Обычный',
      feed_text_link: 'Ссылка',
      feed_text_link_href: 'Адрес, пусто — снять ссылку',
      feed_text_clear: 'Убрать оформление',
      feed_string_over: 'при сохранении хвост обрежется',
      feed_image_none: 'изображения нет',
      feed_image_choose: 'выбрать файл',
      feed_image_not_chosen: 'файл не выбран',
      feed_image_upload: 'загрузить',
      feed_image_crop: 'обрезать',
      feed_image_back: 'к изображению',
      feed_image_name_from: 'имя файла взять из',
      feed_image_alt_from: 'alt взять из',
      feed_image_name_bad: 'в имени файла только латиница, цифры и дефис',
      feed_image_name_long: 'имя файла длиннее допустимого:',
      feed_image_min: 'минимум',
      feed_image_current: 'текущий',
      feed_image_paste: 'или вставьте из буфера, Ctrl+V',
      feed_image_delete_ask: 'Удалить изображение?',
      feed_position: 'Позиция',
      feed_show_on_list: 'Список',
      feed_list_format: 'Формат',
      feed_list_format_help: 'Маска даты для списка, буквы PHP: d m y Y H i s. Пусто — как в базе',
      feed_visible: 'Видимость',
      feed_visible_any: 'показать все записи',
      feed_visible_only: 'показать только видимые',
      feed_hidden_only: 'показать только скрытые',
      feed_slug: 'Slug',
      feed_slug_from: 'Slug',
      feed_slug_from_help: 'Делать slug записи из этого поля. Источник один на ленту, повторный выбор снимает его',
      feed_group_link: 'Связи',
      feed_link_choose: 'выбрать',
      feed_link_feed: 'Лента',
      feed_link_field: 'Поле, которое видит оператор',
      feed_link_same_group: 'Связать можно только с лентой этой группы',
      feed_group_bool: 'Boolean',
      feed_group_date: 'Дата',
      feed_group_string: 'Строки',
      feed_no_free_slot: 'Свободных слотов этого типа не осталось',
      feed_save_schema: 'Сохранить схему',
      feed_list_order: 'Порядок записей',
      feed_list_order_help: 'С этого порядка открывается список. Только строковое поле или дата: сортирует база, а у поля json-контейнера своей колонки нет',
      feed_list_order_own: 'свой порядок ленты',
      feed_list_order_asc: 'по возрастанию',
      feed_list_order_desc: 'по убыванию',
      feed_view_article: 'Статья для показа',
      feed_view_article_help: 'Имя статьи, которой сайт показывает запись. Адрес записи — /<статья>/<slug>, и ссылка на него появляется в форме записи. Пусто — ссылки нет',
      feed_view_item: 'Посмотреть',
      feed_form_order: 'Порядок в форме записи',
      feed_form_order_help: 'Порядок полей на странице записи. Поля здесь все: спрятанное из формы поле нечем заполнить',
      api_error: 'Ошибка',
      api_bad_request: 'Ошибка в запросе',
      api_network: 'Ошибка сети',
      api_bad_answer: 'Невалидный ответ',
      api_unknown: 'Неизвестная ошибка',
      api_link_copied: 'Скопирована ссылка',
      api_link_copy_error: 'Ошибка копирования ссылки',
      art_cut: 'Вырезано:',
      art_pasted: 'Вставлено',
      art_created: 'Создано',
      art_root_keep: 'Не стоит удалять root',
      art_delete_ask: 'Удалить ?',
      art_delete_no_parent: 'Ошибка удаления: parent не найден',
      art_delete_failed: 'Ошибка удаления элемента, перезагрузите',
      art_deleted: 'Удалено',
      art_copied: 'Скопировано',
      art_export: 'Экспорт',
      check_articles: 'Проверка статей',
      check_hint: 'Находит и сразу чинит; что починено — в отчёте',
      check_done: 'Починено',
      check_clean: 'Чинить было нечего',
      check_reports: 'Отчёты',
      check_reports_empty: 'пока нет',
      imp_file: 'Файл',
      imp_date: 'Дата',
      imp_size: 'Размер',
      imp_mode: 'Режим',
      imp_partial: 'Частичный',
      imp_full: 'Полный',
      imp_mode_hint: 'Частичный цепляет дерево из файла к сайту. Полный сносит сайт и поднимает файл на его место.',
      imp_check: 'Проверить',
      imp_check_first: 'Импорт открывает чистая проверка',
      imp_run: 'Импорт',
      imp_run_ask: 'Импортировать? Сайт изменится.',
      imp_no_file: 'Файл не выбран',
      imp_report_ok: 'Файл годится, импорт открыт',
      imp_report_bad: 'Файл не годится',
      imp_done: 'сделано',
      imp_done_all: 'Готово',
      imp_file_failed: 'Файлы статьи {name} не записались: {error}. Дерево импортировано; поправь эту статью и сохрани — повторять импорт не надо.',
      imp_attach_root: 'Файл вешает {name} на {parent}, а такой статьи на сайте нет: {name} уходит в корень последним листом',
      imp_clean: 'Ошибок нет, сайт ничего не теряет',
      imp_trees_hint: 'Берёза — дерево из файла, дуб — дерево сайта. В отчёт идут только ошибки и коллизии: где имя совпало с именем, статья дуба уходит со всем, что под ней.',
      imp_replace: 'Статья {name} есть в берёзе и в дубе — дубовая будет удалена',
      imp_drop: 'Родитель {parent}: берёза не имеет статьи {name}, есть в дубе, будет удалена',
      imp_e_json: 'Файл не разбирается как json',
      imp_e_not_list: 'В файле не список статей',
      imp_e_empty: 'В файле нет статей',
      imp_e_row: 'Строка {line}: это не статья',
      imp_e_name: 'Строка {line}: нет имени',
      imp_e_name_bad: 'Строка {line}: имя {name} — только латинские буквы, цифры, дефис и подчёркивание',
      imp_e_dup: 'Имя {name} встречается в файле дважды',
      imp_e_root_partial: 'В файле есть root: такой файл поднимается только полным импортом',
      imp_e_ring: 'В файле кольцо: статьи ссылаются друг на друга по кругу',
      art_drag_error: 'Ошибка перетаскивания',
      art_not_selected: 'Статья не выделена',
      art_help: 'Справка',
      art_find: 'найти',
      feed_conditions: 'Условия',
      feed_sort_asc: 'по возрастанию',
      feed_sort_desc: 'по убыванию',
      feed_per_page_after: 'записей на странице',
      feed_field_visible: 'видимость',
      feed_field_created: 'дата создания',
      feed_field_updated: 'дата изменения',
      feed_sorting: 'Сортировка',
      feed_pagination: 'Пагинация',
      feed_size_mb: 'МБ',
      feed_size_kb: 'КБ',
      feed_recipe_by_id: 'Запись по id',
      feed_recipe_create: 'Создать запись',
      feed_recipe_change: 'Изменить запись по id',
      feed_recipe_remove: 'Удалить запись по id',
      feed_recipe_list: 'Билдер списка',
      feed_tab_data: 'Данные',
      feed_tab_structure: 'Структура',
      feed_string_help: 'Code — имя, которым пользуется приложение. Label — подпись в админке. default — значение новой записи. Unic — значение должно быть уникальным внутри ленты. validation — правила Laravel одной строкой, например: required|string|min:3|max:255',
      feed_cut_done: 'Вырезано:',
      feed_group_delete_ask: 'Удалить группу?',
      feed_feed_delete_ask: 'Удалить ленту?',
      feed_feed_not_empty: 'В ленте есть записи, она не удаляется',
      feed_paste_done: 'Перенесено',
      feed_feeds_count: 'Лент',
      feed_group: 'Группа',
      feed_items_count: 'Записей',
      feed_name: 'Лента',
      feed_no_feeds: 'В группе нет лент',
      feed_no_groups: 'Групп пока нет',
      feed_title: 'Ленты',
      mail_tab_messages: 'Сообщения',
      mail_tab_addresses: 'Емайлы',
      mail_address_email: 'Емайл',
      mail_address_blocked: 'Блокировка',
      mail_sent: 'Отправленные',
      mail_queue: 'В очереди',
      mail_from: 'Отправитель',
      mail_to: 'Получатель',
      mail_subject: 'Тема',
      mail_sent_at: 'Отправлено',
      mail_scheduled_at: 'Запланировано',
      mail_attempts: 'Попытки',
      mail_status: 'Статус',
      mail_errors_title: 'Ошибки доставки',
      mail_no_errors: 'Ошибок нет',
      mail_delete_confirm: 'Удалить это письмо?',
      mail_deleted: 'Письмо удалено',
      mail_empty: 'Писем нет',
      mail_load_more: 'Показать ещё',
      mail_status_queued: 'В очереди',
      admin_new_password: 'Пароль нового админа',
      admin_new_password_once: 'Скопируйте сейчас: показывается один раз. Забытый меняется правкой.',
      admin_password_keep: 'новый пароль, пусто — не меняется',
      mail_status_sending: 'Отправляется',
      mail_status_sent: 'Отправлено',
      mail_status_delivered: 'Доставлено',
      mail_status_open: 'Открыто',
      mail_status_retrying: 'Ошибка доставки',
      mail_status_failed: 'Сбой',
      mail_status_emailblocked: 'Заблокировано',
      mail_details_title: 'Письмо',
      mail_details_button: 'Подробнее',
      mail_reply_to: 'Reply-To',
      mail_close: 'Закрыть',
      mail_raw_title: 'Raw письмо',
      mcp_agent: 'Агент',
      mcp_command: 'Команда запуска',
      mcp_start: 'старт',
      mcp_password: 'Пароль',
      mcp_password_title: 'Дополнительный пароль',
      mcp_no_config: 'Нет configAI.php, раздел не работает. Файл ждут здесь',
      mcp_no_password: 'Пароль пустой, раздел выключен. Задайте пароль в файле',
      mcp_no_rules: 'У агента нет правил, запуск не даётся. Файл ждут здесь:',
      mcp_no_agents: 'В configAI.php нет агентов',
      mcp_session: 'Сеанс',
      mcp_started: 'Сеанс запущен',
      mcp_reread: 'Перечитать',
      mcp_reread_help: 'Показать всё, что ушло вверх за край экрана',
      mcp_send: 'Отправить',
      mcp_send_hint: 'Ctrl+Enter — отправить, Enter — перенос строки',
      mcp_finish: 'Завершить',
      mcp_finish_title: 'Чем завершить',
      mcp_closing: 'Команда завершения отправлена',
      mcp_stopped: 'Сеанс закончен',
      mcp_leave: 'Агент ещё работает. Уйти со страницы?',
      mcp_prompts: 'Промпты',
      mcp_prompt_add: 'Добавить промпт',
      mcp_prompt_name: 'Название',
      mcp_prompt_text: 'Текст промпта',
      mcp_prompts_empty: 'Пока ничего не сохранено',
      mcp_prompts_saved: 'Промпты сохранены',
      mcp_close: 'Закрыть',
      mcp_kill_all: 'Убить мои сеансы',
      mcp_kill_help: 'Убивает всех агентов, запущенных тобой, здесь и на других вкладках',
      mcp_kill_confirm: 'Убить все свои сеансы агента?',
      mcp_killed: 'Убито сеансов',

      archive: 'Архив',
      archive_empty: 'Версий пока нет: архив начинается с первого сохранения',
      archive_when: 'Когда',
      archive_who: 'Кто',
      archive_body: 'Блейд статьи',
      archive_controller: 'Контроллер',
      archive_copy_hint: 'Текст только для чтения: возьми кусок и закрой или восстанови версию целиком.',
      archive_back: 'К списку',
      archive_restore: 'Восстановить',
      archive_restore_confirm: 'Восстановить эту версию? Статья, какая есть сейчас, уйдёт в архив.',
      archive_restored: 'Версия восстановлена',
      archive_exit: 'Выход',
      archive_days_now: 'Архив версий статей хранится {days} дней',
      archive_days_forever: 'Архив версий статей хранится вечно',
      archive_purge: 'Удалить версии удалённых статей',
      archive_purge_confirm: 'Удалить версии статей, которых больше нет? Обратного пути не будет.',
      archive_purged: 'Удалено версий',
      archive_no_deleted: 'от удалённых статей ничего нет',

      mcp_title: 'Токен для МСП по https',
      mcp_intro: 'С этим токеном агент на твоей машине работает с сайтом через инструменты МСП и больше никак.',
      mcp_no_token: 'Токена нет. Адрес отвечает 401 всем.',
      mcp_issued: 'Выдан',
      mcp_last_used: 'Последний вызов',
      mcp_ip: 'Адрес',
      mcp_state: 'Состояние',
      mcp_alive: 'Живой: {idle} мин без вызовов, {life} мин жизни',
      mcp_dead: 'Протух, бери новый',
      mcp_get: 'Получить токен',
      mcp_get_again: 'Получить новый',
      mcp_reissue_confirm: 'Новый токен убьёт старый, работающий с ним агент встанет. Продолжаем?',
      mcp_revoke: 'Отозвать',
      mcp_revoke_confirm: 'Отозвать токен? Агент встанет сразу.',
      mcp_revoked: 'Токен отозван',
      mcp_once: 'Токен показывается один раз. Копируй сейчас: на сайте остался только хеш.',
      mcp_copy: 'Копировать',
      mcp_copied: 'Скопировано',
      mcp_url: 'Адрес МСП',
      mcp_export_hint: 'Перед тем как пустить агента, сделай экспорт корня: правый клик по root в дереве → «Экспорт». Откатить — импорт этого файла в режиме «полный».',
      yes: 'Да',
    },
  },
});

export const i18nReady = new Promise((resolve) => {
  (async () => {
    const result = await apiSetup({
      command: 'getIniParams',
    });
    const loc = result?.LANGUAGE || 'en'; //
    console.log(loc);
    i18n.global.locale.value = loc;
    resolve(loc);
  })();
});

export default i18n;
