// import { useI18n } from 'vue-i18n';
// const { t } = useI18n();

//  t('save')
//  {{ t('reset') }}

import { apiSetup, apiCall } from '../apiCall';

import { createI18n } from 'vue-i18n';

const i18n = createI18n({
  legacy: false,
  locale: 'ru',
  fallbackLocale: 'en',
  messages: {
    en: {
      add: 'Add',
      add_route_params: 'Add parameter',
      autocomplete_controller: 'Autocomplete',
      autocomplete_liveWare_controller: 'LiveWire controller',
      autocomplete_simple_controller: 'Controller',
      available_all_params: 'Any parameters allowed',
      available_selected_params: 'Only selected allowed',
      bind_params: 'Bind parameters',
      blade_comment: 'Blade comments',
      blade_snippet: 'Blade snippets',
      cache_created: 'Cache created',
      cache_published: 'Cache published',
      cancel: 'Cancel',
      choose_files: 'Choose files',
      copy_as_imgcode: 'Copy Img',
      copy_path: 'Copy path',
      crawler: 'Crawler',
      create: 'Create',
      create_file: 'Create file',
      create_folder: 'Create folder',
      delete: 'Delete',
      delete_published_cache: 'Delete published cache',
      delete_storage: 'Delete storage',
      duplicate_overwrite: 'Duplicate — will be overwritten',
      edit: 'Edit',
      enter_number: 'Enter number',
      error: 'Error',
      errors: 'Errors',
      file_name: 'File name',
      file_saved: 'File saved',
      file_was_loaded: 'Loaded',
      formatted: 'Formatted',
      go_selected: 'Go to article by selected word',
      goto_article: 'Go to article',
      is_route: 'Route enabled',
      menu_on: 'Visible in menu',
      name_file: 'File name',
      name_folder: 'Folder name',
      new_name: 'New name',
      no: 'No',
      now_reading: 'Checking now',
      ok: 'Ok',
      only_admin: 'Admin only',
      publish_storage: 'Publish storage',
      public_deleted: 'Public deleted',
      ready: 'Ready',
      ready_url_rout: 'Ready URL',
      rename: 'Rename',
      reset: 'Reset',
      route_params: 'Route parameters',
      save: 'Save',
      saved: 'Saved',
      setup_reset: 'Settings reset',
      setup_saved: 'Settings saved',
      start: 'Start',
      stop: 'Stop',
      storage_deleted: 'Storage deleted',
      submit: 'Done',
      total: 'Total',
      upload: 'Upload',
      upload_files: 'File upload',
      url_saved: 'URL saved',
      use_controller: 'Use controller',
      use_getpatams: 'Use GET parameters',
      utm_enable: 'Enable UTM ?=utm...',
      user_list_loaded: 'List loaded',
      was_deleted: 'Deleted ',
      yes: 'Yes',
    },

    ru: {
      add: 'Добавить',
      add_route_params: 'Добавить параметр',
      autocomplete_controller: 'Автозаполнение',
      autocomplete_liveWare_controller: 'LiveWare контроллер',
      autocomplete_simple_controller: 'Контроллер',
      available_all_params: 'Доступны любые параметры',
      available_selected_params: 'Доступны только',
      bind_params: 'Привязывать параметры',
      blade_comment: 'комментарии блейда',
      blade_snippet: 'снипеты блейда',
      cache_created: 'Кеш создан',
      cache_published: 'Кеш опубликован',
      cancel: 'Отмена',
      choose_files: 'Выбрать файлы',
      copy_as_imgcode: 'Копировать Img',
      copy_path: 'Копировать путь',
      crawler: 'Краулер',
      create: 'Создать',
      create_file: 'Создать файл',
      create_folder: 'Создать папку',
      delete: 'Удалить',
      delete_published_cache: 'Удалить опубликованный кеш',
      delete_storage: 'Удалить storage',
      duplicate_overwrite: 'копия, будет переписан',
      edit: 'Редактировать',
      enter_number: 'Введите число',
      error: 'Ошибка',
      errors: 'Ошибки',
      file_name: 'Имя файла',
      file_saved: 'Файл сохнанен',
      file_was_loaded: 'Загружен',
      formatted: 'Отформатировано',
      go_selected: 'перейти в статье по выбранному слову',
      goto_article: 'перейти на статью',
      is_route: 'Раут включен',
      menu_on: 'Видно в меню',
      name_file: 'Имя файла',
      name_folder: 'Имя папки',
      new_name: 'Новое имя',
      no: 'Нет',
      now_reading: 'Сейчас проверяется',
      ok: 'Ок',
      only_admin: 'Только Админ',
      publish_storage: 'Опубликовать storage',
      public_deleted: 'Public удален',
      ready: 'Готово',
      ready_url_rout: 'Готовый url',
      rename: 'Переименовать',
      reset: 'Сбросить',
      route_params: 'Параметры маршрута',
      save: 'Сохранить',
      saved: 'Сохранено',
      setup_reset: 'Параметры сброшены',
      setup_saved: 'Параметры сохранены',
      start: 'Старт',
      stop: 'Стоп',
      storage_deleted: 'Storage удален',
      submit: 'Готово',
      total: 'Всего',
      upload: 'Загрузить',
      upload_files: 'Загрузка файлов',
      url_saved: 'url_сохранен',
      use_controller: 'Испольовать контроллер',
      use_getpatams: 'Использовать GET параметры',
      utm_enable: 'Разрешить Utm ?=utm...',
      user_list_loaded: 'Список считан',
      was_deleted: 'Удален ',
      yes: 'Да',
    },
  },
});

export const i18nReady = new Promise((resolve) => {
  (async () => {
    const result = await apiSetup({
      command: 'getIniParams',
    });
    const loc = result?.LANGUAGE || 'en'; //
    console.log(loc);
    i18n.global.locale.value = loc;
    resolve(loc);
  })();
});

export default i18n;
